package burp;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DefaultTabPane extends Component {
    private JPanel mainPanel;
    private JPanel topPanel;
    private JPanel bottomPanel;

//    public static void main(String[] args) {
//        JFrame frame = new JFrame("DefaultTabPane");
//        frame.setContentPane(new DefaultTabPane().mainPanel);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//    }

    private JTextField iv;
    private JComboBox algComboBox;
    private JTextField secretKey;
    private JTextField reqSepParamText;
    private JCheckBox reqURLCheckBox;
    private JTextField respSepParam;
    private JCheckBox respURLCheckBox;


    private JRadioButton specificParam;
    private JRadioButton CompleteBody;
    private JPanel respSettingPanel;
    private JPanel reqSettingPanel;
    private JPanel globalSettingPanel;
    private JRadioButton reqBodyBtn;
    private JRadioButton reqParamBtn;
    private JRadioButton respBodyBtn;
    private JRadioButton respParamBtn;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("DefaultTabPane");
        frame.setContentPane(new DefaultTabPane().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, 20));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setOrientation(0);
        mainPanel.add(splitPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        splitPane1.setLeftComponent(topPanel);
        globalSettingPanel = new JPanel();
        globalSettingPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        topPanel.add(globalSettingPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        globalSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "golobal setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("type");
        CellConstraints cc = new CellConstraints();
        globalSettingPanel.add(label1, cc.xy(1, 1, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("key");
        globalSettingPanel.add(label2, cc.xy(1, 3, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        algComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("aes/ecb/128/nopadding");
        defaultComboBoxModel1.addElement("aes/cbc/128/nopadding");
        algComboBox.setModel(defaultComboBoxModel1);
        globalSettingPanel.add(algComboBox, cc.xy(3, 1));
        iv = new JTextField();
        globalSettingPanel.add(iv, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("iv");
        globalSettingPanel.add(label3, cc.xy(1, 5, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        secretKey = new JTextField();
        secretKey.setText("");
        globalSettingPanel.add(secretKey, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        reqSettingPanel = new JPanel();
        reqSettingPanel.setLayout(new FormLayout("fill:d:noGrow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        topPanel.add(reqSettingPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        reqSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "request setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        reqURLCheckBox = new JCheckBox();
        reqURLCheckBox.setInheritsPopupMenu(false);
        reqURLCheckBox.setSelected(false);
        reqURLCheckBox.setText("URL Decode/Encode");
        reqSettingPanel.add(reqURLCheckBox, cc.xy(1, 7));
        reqSepParamText = new JTextField();
        reqSettingPanel.add(reqSepParamText, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        reqParamBtn = new JRadioButton();
        reqParamBtn.setName("reqParam");
        reqParamBtn.setSelected(false);
        reqParamBtn.setText("Specific request parameters (separated with space)");
        reqSettingPanel.add(reqParamBtn, cc.xy(1, 3));
        reqBodyBtn = new JRadioButton();
        reqBodyBtn.setName("reqParam");
        reqBodyBtn.setText("Complete request body");
        reqSettingPanel.add(reqBodyBtn, cc.xy(1, 1));
        respSettingPanel = new JPanel();
        respSettingPanel.setLayout(new FormLayout("fill:d:noGrow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        topPanel.add(respSettingPanel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        respSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "response setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        respSepParam = new JTextField();
        respSettingPanel.add(respSepParam, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        respURLCheckBox = new JCheckBox();
        respURLCheckBox.setText("URL Decode/Encode");
        respSettingPanel.add(respURLCheckBox, cc.xy(1, 7));
        respBodyBtn = new JRadioButton();
        respBodyBtn.setText("Complete response body");
        respSettingPanel.add(respBodyBtn, cc.xy(1, 1));
        respParamBtn = new JRadioButton();
        respParamBtn.setText("Specific response parameters (separated with space)");
        respSettingPanel.add(respParamBtn, cc.xy(1, 3));
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        splitPane1.setRightComponent(bottomPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
