package burp;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

class TestTab extends JPanel{
    private JPanel mainPanel;
    private JPanel topPanel;
    private JTextField iv;
    private JComboBox algComboBox;
    private JTextField secretKey;
    private JTextField reqSepParamText;
    private JCheckBox reqURLCheckBox;
    private JTextField respSepParam;
    private JCheckBox respURLCheckBox;


    private JPanel respSettingPanel;
    private JPanel reqSettingPanel;
    private JPanel globalSettingPanel;
    private JRadioButton reqBodyBtn;
    private JRadioButton reqParamBtn;
    private JRadioButton respBodyBtn;
    private JRadioButton respParamBtn;
    private JTextField textField1;
    private JButton startButton;
    private JTabbedPane inputTablePanel;
    private JButton encryptButton;
    private JButton clearButton;
    private JCheckBox URLEncodeDecodeCheckBox;
    private JPanel outputTextFiled;
    private JTextArea inputTextArea;
    private JTextArea outputTextArea;

    public TestTab() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setOrientation(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(splitPane1, gbc);
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        splitPane1.setLeftComponent(topPanel);
        globalSettingPanel = new JPanel();
        globalSettingPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        topPanel.add(globalSettingPanel, gbc);
        globalSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "golobal setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        globalSettingPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("key");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        globalSettingPanel.add(label2, gbc);
        algComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("AES/CBC/NoPadding");
        defaultComboBoxModel1.addElement("AES/CBC/PKCS5Padding");
        defaultComboBoxModel1.addElement("AES/ECB/NoPadding");
        defaultComboBoxModel1.addElement("AES/ECB/PKCS5Padding");
        defaultComboBoxModel1.addElement("AES/GCM/NoPadding");
        defaultComboBoxModel1.addElement("DES/CBC/NoPadding");
        algComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        globalSettingPanel.add(algComboBox, gbc);
        iv = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        globalSettingPanel.add(iv, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("iv");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        globalSettingPanel.add(label3, gbc);
        secretKey = new JTextField();
        secretKey.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        globalSettingPanel.add(secretKey, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        globalSettingPanel.add(textField1, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Traget Host");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        globalSettingPanel.add(label4, gbc);
        startButton = new JButton();
        startButton.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        globalSettingPanel.add(startButton, gbc);
        reqSettingPanel = new JPanel();
        reqSettingPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        topPanel.add(reqSettingPanel, gbc);
        reqSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "request setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        reqURLCheckBox = new JCheckBox();
        reqURLCheckBox.setInheritsPopupMenu(false);
        reqURLCheckBox.setSelected(false);
        reqURLCheckBox.setText("URL Decode/Encode");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        reqSettingPanel.add(reqURLCheckBox, gbc);
        reqSepParamText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        reqSettingPanel.add(reqSepParamText, gbc);
        reqParamBtn = new JRadioButton();
        reqParamBtn.setName("reqParam");
        reqParamBtn.setSelected(false);
        reqParamBtn.setText("Specific request parameters (separated with space)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        reqSettingPanel.add(reqParamBtn, gbc);
        reqBodyBtn = new JRadioButton();
        reqBodyBtn.setName("reqParam");
        reqBodyBtn.setText("Complete request body");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        reqSettingPanel.add(reqBodyBtn, gbc);
        respSettingPanel = new JPanel();
        respSettingPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        topPanel.add(respSettingPanel, gbc);
        respSettingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "response setting", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, null, null));
        respSepParam = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        respSettingPanel.add(respSepParam, gbc);
        respURLCheckBox = new JCheckBox();
        respURLCheckBox.setText("URL Decode/Encode");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        respSettingPanel.add(respURLCheckBox, gbc);
        respBodyBtn = new JRadioButton();
        respBodyBtn.setText("Complete response body");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        respSettingPanel.add(respBodyBtn, gbc);
        respParamBtn = new JRadioButton();
        respParamBtn.setText("Specific response parameters (separated with space)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        respSettingPanel.add(respParamBtn, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        splitPane1.setRightComponent(panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.NORTH);
        encryptButton = new JButton();
        encryptButton.setText("Encrypt");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(encryptButton, gbc);
        JButton decryptButton = new JButton();
        decryptButton.setText("Dcrypt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(decryptButton, gbc);
        clearButton = new JButton();
        clearButton.setText("Clear");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(clearButton, gbc);
        URLEncodeDecodeCheckBox = new JCheckBox();
        URLEncodeDecodeCheckBox.setText("URL Encode/Decode");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(URLEncodeDecodeCheckBox, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel1.add(panel3, BorderLayout.CENTER);
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(tabbedPane1, gbc);
        outputTextFiled = new JPanel();
        outputTextFiled.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Output", outputTextFiled);
        outputTextArea = new JTextArea();
        outputTextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        outputTextFiled.add(outputTextArea, gbc);
        inputTablePanel = new JTabbedPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(inputTablePanel, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        inputTablePanel.addTab("Input", panel4);
        inputTextArea = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(inputTextArea, gbc);
        this.add(mainPanel);
    }
}
